[tasks.build_image]
description = "Build the image"
run = "docker build --platform linux/amd64 -t ghcr.io/felixandersen/sneak-link:$(cat VERSION) ."

[tasks.push_image]
description = "Push the image"
run = [
  "echo $CR_PAT | docker login ghcr.io -u felixandersen --password-stdin",
  "docker tag ghcr.io/felixandersen/sneak-link:$(cat VERSION) ghcr.io/felixandersen/sneak-link:latest",
  "docker push ghcr.io/felixandersen/sneak-link:$(cat VERSION)",
  "docker push ghcr.io/felixandersen/sneak-link:latest"
]

[tasks.build_and_push_image_dev]
description = "Push the image to development server for testing"
run = [
  "docker build --platform linux/amd64 -t ghcr.io/felixandersen/sneak-link:dev .",
  "docker save ghcr.io/felixandersen/sneak-link:dev | ssh -C $DEV_SSH_HOST docker load"
]

[tools]
node = "latest"
