name: Build and push docker image

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  build_and_release_image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: false # no need to install node, we only need mise for task running
      - run: mise run build_image
      - run: mise run push_image
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
